apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - route.yaml

images:
  - name: quarkus
    newName: quay.io/rh_ee_lfalero/ux-hello-java
    newTag: 1.0.0